config/routes.rb
Rails.application.routes.draw do
  get 'maps/index' => 'maps#index'
  resources :maps, only: [:index]

  devise_for :users
  resources :movies, only: [:index, :show]
  get '' => 'home#top'
  get 'genre' => 'home#genre'
  get 'search' => 'home#search'
  get 'amazon' => 'home#amazon'
  get 'unext' => 'home#unext'
  get 'netflix' => 'home#netflix'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :directors, through: :movie_directors
  has_many :movie_directors
  has_many :performers, through: :movie_performers
  has_many :movie_performers
  has_many :genres, through: :movie_genres
  has_many :movie_genres
  has_many :movie_subscriptions
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
  belongs_to :director
  belongs_to :movie
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/movie_performer.rb
class MoviePerformer < ApplicationRecord
  belongs_to :performer
  belongs_to :movie
end

app/models/movie_subscription.rb
class MovieSubscription < ApplicationRecord
end

app/models/performer.rb
class Performer < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @desc = Movie.all.order(id: :desc).limit(3)
    @asc = Movie.all.order(id: :asc).limit(3)
    @random = Movie.all.order("RANDOM()").limit(5)
  end
  
  def login
  end
  
  def signup
  end
  
  def movies
  end
  
  def genre
    @search = params[:search]
    @genre_id = params[:genre_id]
    @movies = Movie.where('title like ?', "%#{@search}%")
    @moveis = @movies.joins(:genres).where('genres.id = ?', @genre_id) if @genre_id.present?
  end
  
  def search
    @search = params[:search]
    @genre_id = params[:genre_id]
    @subscription_id = params[:subscription_id]
    @movies = Movie.all
    @movies = @movies.where('title like ?', "%#{@search}%") if @search.present?
    @movies = @movies.joins(:movie_genres).where('movie_genres.genre_id = ?', @genre_id) if @genre_id.present?
    @movies = @movies.joins(:movie_subscriptions).where('movie_subscriptions.subscription_id = ?', @subscription_id) if @subscription_id.present?
  end
  
  def amazon
  end
  
  def unext
  end
  
  def netflix
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/amazon.html.erb
<body>  
  <div class="container">
    <ul class="list-unstyled row my-5 border p-3">
      <li class="media col-4">
        <a href="amazon">
        <img class="mr-3" src=https://d2ueuvlup6lbue.cloudfront.net/attachments/8a1c9488a54b096d899024477fdd4cf39fedb3e4/store/fit/64/64/8fef5edb6b0371357e973f03ea3d72d395f5b411c37ea7ee06f8804fa059/_.png>
        <div class="media-body">
          <h5 class="mt-0 mb-1">Amazon Prime Video</h5>
        </a>
        </div>
      </li>
      <li class="media col-4">
        <a href="netflix">
        <img class="mr-3" src=https://d2ueuvlup6lbue.cloudfront.net/attachments/7e34c5651f033fdb200fb5136b8386a9ce80a8b6/store/fit/64/64/16aa6c4e0304b713193a96ccbfa3e4861fa0753bb4e5841e38121a3d0bfd/_.png>
        <div class="media-body">
          <h5 class="mt-0 mb-1">Netflix</h5>
        </a>  
        </div>
      </li>
      <li class="media col-4">
        <a href="unext">
        <img class="mr-3" src=https://d2ueuvlup6lbue.cloudfront.net/attachments/4d65196d0c1678b1ff37228d932cc9b5893766f6/store/fit/64/64/ebe835891a26d1285991c648ef1a373417944c1e313cc47bce45dda18379/_.png>
        <div class="media-body">
          <h5 class="mt-0 mb-1">U-NEXT</h5>
        </a>  
        </div>
      </li>
    </ul>
    <h3 class="row justify-content-md-center my-5">Amazon Prime Videoで鑑賞できる作品</h3>
    <div class="card mb-5">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img style="height: 400px; width: 100%; object-fit: contain; background-color: black;" src="https://d2ueuvlup6lbue.cloudfront.net/attachments/9fd6f2937233b6ff9f4f8950494357b0e5ba6782/store/fitpad/300/400/602643410621dccb9cac41f90c5fa0c50956c53e2b32558e94adfa3310fa/_.jpg" class="mw-100" alt="...">
        </div>
        <div class="col-md-8 row ml-2">
          <div class="card-body">
            <h3 class="card-title mb-4">映画タイトル</h3>
            <p class="card-text">評価　上映時間　上映年</p>
            <p class="card-text">ここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書く</small></p>
          </div>
          <ul class="list-group list-group-flush col-2 ml-3">
            <li class="list-group-item">監督</li>
            <li class="list-group-item">出演</li>
            <li class="list-group-item">ジャンル</li>
          </ul>
          <ul class="list-group list-group-flush col-4 ml-3">
            <a href="#" class="list-group-item list-group-item-action">監督</a>
            <a href="#" class="list-group-item list-group-item-action">出演</a>
            <a href="#" class="list-group-item list-group-item-action">ジャンル</a>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="card text-center">
    <div class="card-header">
      <a href="#" class="btn btn-primary">トップへ戻る</a>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>映画サービス</p>
      </blockquote>
    </div>
  </div>

 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

app/views/home/genre.html.erb
<body>  
  <div class="container">
    <h3 class="text-center mt-5">アクションのおすすめ作品</h3>
    <div class="row my-5">
      <div class="list-group col-3">
        <a href="#" class="list-group-item list-group-item-action active">
          アクション(〇〇件)
        </a>
        <a href="#" class="list-group-item list-group-item-action">ホラー</a>
        <a href="#" class="list-group-item list-group-item-action">アニメ</a>
        <a href="#" class="list-group-item list-group-item-action">SF</a>
        <a href="#" class="list-group-item list-group-item-action">コメディ</a>
      </div>
      <% @movies.each do |movie| %>
      <div class="card col-9">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img style="height: 400px; width: 100%; object-fit: contain; background-color: white;" src="<%= movie.thumbnail_url %>" class="mw-100" alt="...">
        </div>
        <div class="col-md-8 row ml-2">
          <div class="card-body">
            <h3 class="card-title mb-4">映画タイトル</h3>
            <p class="card-text">評価　上映時間　上映年</p>
            <p class="card-text">ここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書くここにあらすじを書く</small></p>
          </div>
          <ul class="list-group list-group-flush col-3 ml-3">
            <li class="list-group-item">監督</li>
            <li class="list-group-item">出演</li>
            <li class="list-group-item">ジャンル</li>
          </ul>
          <ul class="list-group list-group-flush col-5 ml-3">
            <a href="#" class="list-group-item list-group-item-action">監督</a>
            <a href="#" class="list-group-item list-group-item-action">出演</a>
            <a href="#" class="list-group-item list-group-item-action">ジャンル</a>
          </ul>
        </div>
      </div>
    </div>
    <% end %>
    </div>
  </div>
    
  <div class="card text-center">
    <div class="card-header">
      <a href="#" class="btn btn-primary">トップへ戻る</a>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>映画サービス</p>
      </blockquote>
    </div>
  </div>
    
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

app/views/home/login.html.erb
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>fMovie</title>
  </head>
  
  <body>
  <div class="row justify-content-md-center mt-5">
    <div class="col-6 border p-4">
    <form>
      <div class="row justify-content-md-center pb-4">
        <h2>ログイン</h2>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">メールアドレス</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">パスワード</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
      <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" class="btn btn-primary">ログイン</button>
    </form>
    </div>
  </div>  
    
  </body>

app/views/home/search.html.erb
<body>
  <div class="container">
    <h3 class="text-center mt-5">検索結果に関する映画</h3>
    <% @movies.each do |movie| %>
    <%= link_to movie_path(movie) do %>
    <div class="card my-5">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img style="height: 400px; width: 100%; object-fit: contain; background-color: black;" src="<%= movie.thumbnail_url %>" class="mw-100" alt="...">
        </div>
        <div class="col-md-8 row ml-2">
          <div class="card-body">
            <h3 class="card-title mb-4"><%= movie.title %></h3>
            <p class="card-text">評価　上映時間:<%= movie.screening_time %>　上映年:<%= movie.screening_date.strftime("%Y年%m月%d日") %></p>
            <p class="card-text"><%= movie.description %></small></p>
          </div>
          <table class="table col-11 pl-2">
            <tbody>
              <tr>
                <th scope="row">監督</th>
                <td><%= movie.directors.map(&:name).join('/') %></td>
              </tr>
              <tr>
                <th scope="row">出演</th>
                <td><%= movie.performers.map(&:name).join('/') %></td>
              </tr>
              <tr>
                <th scope="row">ジャンル</th>
                <td><%= movie.genres.map(&:name).join('/') %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>  
  <div class="card text-center">
    <div class="card-header">
      <a href="#" class="btn btn-primary">トップへ戻る</a>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>fMovie</p>
      </blockquote>
    </div>
  </div>

 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>  

app/views/home/signup.html.erb
  <body>
    <div class="row justify-content-md-center mt-5">
    <div class="col-6 border p-4">
    <form>
      <div class="row justify-content-md-center pb-4">
        <h2>会員登録</h2>
      </div>  
      <div class="form-group">
        <label for="validationCustomUsername">ユーザーネーム</label>
      <div class="input-group">
        <input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required>
        <div class="invalid-feedback">
          Please choose a username.
        </div>
      </div>
      </div>  
      <div class="form-group">
        <label for="exampleInputEmail1">メールアドレス</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">パスワード</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
      <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" class="btn btn-primary">会員登録をする</button>
    </form>
    </div>
    </div>
  </body>  
  
  
  
  <div class="box">
  <div class="box-inner">
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <h1>ログイン</h1>
      <div class="box-email">
        <%= f.label :email, "Eメール" %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
      
      
      <div class="box-password">
        <div class="a-row">
          <div class="column-left">
            <%= f.label :password, "パスワード" %>
          </div>
          
          <div class="column-right">
            <%= link_to "パスワードを忘れた場合", new_user_password_path %>
          </div>
          
        </div>
        <%= f.password_field :password, autocomplete: "current-password" %>
      </div>
      
      
      <div class="box-login">
        <%= f.submit "ログイン" %>
        <div class="legal-text">
          続行することで、Hogezonの
          <%= link_to "利用規約", "#" %>
          および
          <%= link_to "プライバシー規約", "#" %>
          に同意するものとみなされます。
        </div>
        <% if devise_mapping.rememberable? %>
          <div class="remember">
            <%= f.check_box :remember_me %>
            <%= f.label :remember, "ログインしたままにする" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="box-newusr">
      <p><span>------------</span> Hogezonの新しいお客様ですか？ <span>------------</span></p>
      <%= link_to "Hogezonアカウントを作成", new_user_registration_path %>
    </div>
  </div>
</div>


<div class="field">
          <div class="form-group">
            <label for="exampleInputEmail1"><%= f.label :email, "Eメールアドレス" %></label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" <%= f.email_field :email, autofocus: true, autocomplete: "email" %>>
          </div>
        </div>
        

<div class="field">
    <div class="form-group">
        <label for="exampleInputPassword1"><%= f.label :password, "パスワード" %></label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password" %>
    </div>
  </div>
  
  
  <div class="actions">
    <button type="submit" class="btn btn-primary"><%= f.submit "会員登録をする" %></button>
  </div>

app/views/layouts/application.html.erb
<html lang="ja">
<html>
  <head>
    <title>fMovie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
      <a class="navbar-brand" href="#">fMovie</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">ホーム <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            <% else %>
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
            <% end %>
          </li>
          <% unless user_signed_in? %>
            <li class="nav-item">
            <%= link_to "会員登録", new_user_registration_path, class: 'nav-link' %>
          </li>
          <% end %>
        </ul>
      </div>
      </div>
    </nav>

    <nav class="navbar navbar-light bg-light">
      <div class="container">
        <div class="row w-100">
          
          <%= form_tag(search_path,:method => 'get', class: 'form-inline w-100') do %>
          <%= text_field_tag :search, @search, class: 'form-control mr-sm-2 col-9', placeholder: "映画・キーワード検索" %>
          <%= submit_tag '検索', :name => nil, class: "btn btn-outline-success my-2 my-sm-0" %>
          <div class="w-100"></div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio1" value="" checked>
            <label class="form-check-label" for="inlineRadio1">すべて</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio1" value="1" <%= @genre_id == '1' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio1">アクション</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio2" value="2"  <%= @genre_id == '2' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">ホラー</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio2" value="3"  <%= @genre_id == '3' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">スリラー</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio2" value="4"  <%= @genre_id == '4' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">アニメ</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio2" value="5"  <%= @genre_id == '5' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">SF</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio2" value="6"  <%= @genre_id == '6' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">アドベンチャー・冒険</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio2" value="7"  <%= @genre_id == '7' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">恋愛</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="genre_id" id="inlineRadio2" value="8"  <%= @genre_id == '8' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">ドラマ</label>
          </div>
          <div class="w-100"></div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="subscription_id" id="inlineRadio1" value="" checked>
            <label class="form-check-label" for="inlineRadio1">すべて</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="subscription_id" id="inlineRadio2" value="1"  <%= @subscription_id == '1' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">Amazon Prime Video</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="subscription_id" id="inlineRadio2" value="2"  <%= @subscription_id == '2' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">U-NEXT</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="subscription_id" id="inlineRadio2" value="3"  <%= @subscription_id == '3' ? 'checked' : '' %>>
            <label class="form-check-label" for="inlineRadio2">Netflix</label>
          </div>
            
          <% end %>
        </div>
      </div>  
    </nav>
  
    
    <%= yield %>
  </body>
</html>

app/views/maps/index.html.erb
<h2>地図</h2>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
let map

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 34.57783663728205, lng:136.53554759999997},
    zoom: 13,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBcnpnyf3eAP9NaGfXzcHM9IkaIQMEkNf8&callback=initMap" async defer></script>

app/views/movies/index.html.erb
<% @movies.each do |post| %>
<a href="/movies/<%= post.id %>">詳細</a>
<% end %>